[package]
name = "euler"
version = "0.1.0"
authors = ["simpajj <simonsalloum@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
num = "0.4.1"
rand = "0.8.5"
